Repository ShabadOS/gurmukhi-utils, pull requests merged in 2020-11, with the labels that each got.

#178 fix(stripEndings): constrain number stripping to end of lines
  README.md
  docs/README.md
  lib/stripEndings.js
  test/stripEndings.spec.js
Labels: Effort: 1 pt, Impact: Low, Status: Merge, Type: Fix

#177 fix(toEnglish): properly detect word boundaries
  lib/toEnglish.js
  test/toEnglish.spec.js
Labels: Effort: 1 pt, Impact: Avg, Status: Merge, Type: Fix

#182 ci: fetch all git history during deploy
  .github/workflows/deploy.yml
  README.md
  docs/README.md
Labels: Effort: 0 pt, Impact: Crit, Status: Merge

#183 ci: fetch complete depth of git history
  .github/workflows/deploy.yml
Labels: Effort: 0 pt, Impact: Crit, Status: Merge
